### ISSUE TITLE
Custom Element v1 scoped styling

### ISSUE THREAD

**Issue by kevinSuttle** [hayatoito/hayatoito.github.io#5]
Thanks for the site. Very useful.

One thing I didn't see was mention of Custom Element v1 scoped styling. 
https://github.com/polymer/polymer/tree/2.0-preview#v1-custom-elements

**Comment by hayatoito** [comment]
Thanks for feedback.

- I think `::content`, `::slotted`,`/deep/`, and `::shadow` are already mentioned.
- Thus, I guess you meant `:host-context()` pseudo-selectors, right?.  This [page](https://github.com/polymer/polymer/tree/2.0-preview#v1-custom-elements) said

> :host-context() pseudo-selectors have been removed.

However, I think this sentence might be confusing. Blink has not removed [`:host-context()`](https://drafts.csswg.org/css-scoping/#selectordef-host-context). You can use `:host-context()' in Blink.

I guess that the intention is that "Polymer 2.0 is no longer using `:host-context()`".

As far as I know, Polymer folks decided to use `:host(:dir(...))`, instead of `:host-context()` because WebKit does not have a plan to support `:host-context()`.
